name: CI | CD Auto Deploy (Main & Test)

on:
  push:
    branches:
      - main
      - test

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to server
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            DEPLOY_PATH="/var/www/teths"
            echo "Deploy başlıyır..."
            echo "Hedef dizin: $DEPLOY_PATH"

            # Papka yoksa oluştur
            echo "Papka yoxlanılır..."
            sudo mkdir -p "$DEPLOY_PATH"

            # Papkanın içine geç
            cd "$DEPLOY_PATH" || exit 1

            # Köhnə fayıl ve papkaları temizle
            echo "Köhnə fayıl və papkalar silinir..."
            sudo find "$DEPLOY_PATH" -mindepth 1 -exec rm -rf {} +

            # Yeni kodları klonla
            echo "Yeni lahiyeni klonlanıyor..."
            git clone https://github.com/Modern-Dentistry/MD-front-end.git .

            # Paketleri yükle
            echo "Pakətlər yüklənir..."
            npm install

            # Build al
            echo "Build alınır..."
            npm run build

            # dist dışındaki her şeyi sil
            echo "dist qalır hər şey silinir..."
            sudo find "$DEPLOY_PATH" -mindepth 1 ! -name 'dist' -exec rm -rf {} +

            echo "Deploy uğurlu!!!!!"
